name: Unit Tests

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  Validate:
    name: Pre deploy validations
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 2.4.2

    - name: Run server tests
      run: deno test --allow-all server/
      
    - name: Run client tests
      run: deno task --cwd client test

  Deploy-nonprod:
    name: Deploy non-prod
    needs: Validate
    runs-on: ubuntu-latest
    environment: nonprod

    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      -  name: Update ECS task definition
         run: |
            aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEF }} > task-def.json

            jq --arg img "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}" \
            '.taskDefinition | .containerDefinitions[0].image = $img | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
            task-def.json > new-task-def.json

            aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Get latest ECS task definition ARN
        id: get-task-def-arn
        run: |
          LATEST_ARN=$(aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEF }} --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "::set-output name=task-def-arn::$LATEST_ARN"

      - name: Update ECS service with latest task definition
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER_NAME }} \
            --service ${{ vars.ECS_SERVICE_NAME }} \
            --task-definition ${{ steps.get-task-def-arn.outputs.task-def-arn }} \
            --force-new-deployment